name: Epic
description: Planejamento de uma iniciativa ampla que agrupa várias features.
title: "[Epic] "
labels: ['epic']
body:
  - type: input
    id: objetivo
    attributes:
      label: Objetivo
      placeholder: 'Ex: Criar sistema de autenticação'
    validations:
      required: true

  - type: textarea
    id: escopo
    attributes:
      label: Escopo e contexto
      description: 'Descreva o que está incluído e o que está fora do escopo'
    validations:
      required: false

  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade
      description: Qual a prioridade deste Epic?
      options:
        - baixa
        - media  
        - alta
        - critica
      default: 0
    validations:
      required: true

  - type: dropdown
    id: tipo-implementacao
    attributes:
      label: Tipo de implementação
      description: Que tipo de implementação este Epic representa?
      options:
        - frontend
        - backend
        - fullstack
        - infrastructure
        - design
        - documentation
        - testing
      default: 0
    validations:
      required: false

  - type: input
    id: sprint
    attributes:
      label: Sprint ou período de execução
      description: Nome da Sprint/Milestone onde este Epic será executado
      placeholder: ex. Sprint 1, Q1 2025, Release 1.0
    validations:
      required: false

  - type: textarea
    id: sub-issues
    attributes:
      label: Sub-issues a serem criadas
      description: 'Liste as Features/Tasks que compõem este Epic. Cada linha se tornará uma issue automática.'
      placeholder: |
        - [ ] Implementar tela de login
        - [ ] Criar API de autenticação  
        - [ ] Implementar recuperação de senha
        - [ ] Configurar middleware de sessão
        - [ ] Criar testes de integração
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Features relacionadas (opcional)
      description: 'Liste features já existentes que fazem parte desta Epic (use #issue para vincular)'
    validations:
      required: false

  - type: textarea
    id: criterios-aceite
    attributes:
      label: Critérios de Aceite do Epic
      description: 'Critérios que definem quando este Epic estará completo'
      placeholder: |
        - [ ] Critério 1
        - [ ] Critério 2  
        - [ ] Critério 3
    validations:
      required: false
