name: Epic
version: 1
description: Planejamento de uma iniciativa ampla que agrupa várias features.
title: "[Epic]"
body:
  - type: input
    id: objetivo
    attributes:
      label: Objetivo da Epic
      placeholder: 'Ex: Criar sistema de autenticação'
    validations:
      required: true

  - type: textarea
    id: escopo
    attributes:
      label: Escopo e contexto
      description: 'Descreva o que está incluído e o que está fora do escopo'
    validations:
      required: false

  - type: textarea
    id: features
    attributes:
      label: Features relacionadas
      description: 'Liste as features que fazem parte desta Epic (use ``- [ ] #issue`` para vincular)'
    validations:
      required: false
