name: Feature
description: Funcionalidade específica que faz parte de uma Epic.
title: "[Feature]"
body:
  - type: input
    id: epic
    attributes:
      label: Epic relacionada
      placeholder: 'Ex: #12'
    validations:
      required: false

  - type: input
    id: objetivo
    attributes:
      label: Objetivo da Feature
      placeholder: 'Ex: Permitir login com e-mail e senha'
    validations:
      required: true

  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos funcionais
      description: 'Liste os requisitos ou critérios de aceite'
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: Tasks relacionadas
      description: 'Liste as tasks que compõem esta feature (use ``- [ ] #issue``)'
    validations:
      required: false
