name: Task
description: Tarefa técnica ou de entrega vinculada a uma Feature.
title: "[Task] "
labels: [enhancement]
body:
  - type: input
    id: objetivo
    attributes:
      label: Objetivo da Task
      placeholder: Ex: Criar componente de input para e-mail
    validations:
      required: true

  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade
      description: Defina o nível de prioridade desta tarefa
      options:
        - Alta
        - Média
        - Baixa
    validations:
      required: true

  - type: dropdown
    id: tipo_implementacao
    attributes:
      label: Tipo de implementação
      description: Selecione se a tarefa é de Frontend ou Backend
      options:
        - Frontend
        - Backend
    validations:
      required: true

  - type: input
    id: milestone
    attributes:
      label: Sprint
      description: Nome exato da milestone (ex: Sprint 1, Sprint 2)
      placeholder: Sprint 1
    validations:
      required: false
