name: Criar Sub-Issues a partir de Epic

on:
  issues:
    types: [opened]

jobs:
  create-subissues:
    runs-on: ubuntu-latest
    steps:
      - name: Criar sub-issues e checklist
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body;
            const parentNumber = issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Função auxiliar para extrair seções
            const extract = (label) => {
              const match = body.match(new RegExp(`### ${label}[\\s\\S]*?\\n(.*?)\\n`, 'i'));
              return match ? match[1].trim() : null;
            };

            // Determinar tipo da issue
            let tipo = 'Task';
            if (issue.title.includes('[Epic]')) tipo = 'Feature';
            else if (issue.title.includes('[Feature]')) tipo = 'Task';

            // Extrair subissues
            const subissuesMatch = body.match(/### Sub-issues a serem criadas[\s\S]*?\n([\s\S]*)/);
            const subissuesRaw = subissuesMatch ? subissuesMatch[1] : '';
            const subissues = subissuesRaw.split('\n').map(l => l.trim()).filter(l => l.length > 0);

            // Campos exclusivos para Task
            let prioridade = null;
            let tipoImplementacao = null;
            let milestoneId = null;

            if (tipo === 'Task') {
              prioridade = extract('Prioridade');
              tipoImplementacao = extract('Tipo de implementação');

              const sprintName = extract('Sprint ou período de execução');
              if (sprintName) {
                const milestones = await github.rest.issues.listMilestones({ owner, repo });
                const found = milestones.data.find(m => m.title === sprintName);
                if (found) milestoneId = found.number;
              }
            }

            // Montar labels
            const labels = [tipo.toLowerCase()];
            if (prioridade) labels.push(`prioridade-${prioridade.toLowerCase()}`);
            if (tipoImplementacao) labels.push(tipoImplementacao.toLowerCase());

            const createdIssues = [];

            // Primeiro, obter o ID do projeto GitHub Projects v2
            const projectQuery = `
              query($owner: String!) {
                organization(login: $owner) {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      title
                      number
                    }
                  }
                }
              }
            `;
            
            let projectId = null;
            try {
              const projectResult = await github.graphql(projectQuery, { owner });
              if (projectResult.organization?.projectsV2?.nodes?.length > 0) {
                // Pega o primeiro projeto encontrado ou você pode filtrar por nome
                projectId = projectResult.organization.projectsV2.nodes[0].id;
                console.log(`Projeto encontrado: ${projectId}`);
              }
            } catch (error) {
              console.log('Erro ao buscar projeto:', error);
            }

            for (const line of subissues) {
              const issuePayload = {
                owner,
                repo,
                title: `[${tipo}] ${line}`,
                body: `Sub-issue de #${parentNumber}`,
                labels
              };

              if (tipo === 'Task' && milestoneId) {
                issuePayload.milestone = milestoneId;
              }

              const newIssue = await github.rest.issues.create(issuePayload);
              const childIssueNumber = newIssue.data.number;

              // Se temos um projeto, adicionar as issues ao projeto e criar relacionamento
              if (projectId) {
                try {
                  // Adicionar a issue pai ao projeto (se ainda não estiver)
                  const addParentMutation = `
                    mutation($projectId: ID!, $contentId: ID!) {
                      addProjectV2ItemByContentId(input: {
                        projectId: $projectId,
                        contentId: $contentId
                      }) {
                        item {
                          id
                        }
                      }
                    }
                  `;

                  const parentGlobalId = Buffer.from(`Issue:${issue.node_id.split('_')[1]}`).toString('base64');
                  const childGlobalId = Buffer.from(`Issue:${newIssue.data.node_id.split('_')[1]}`).toString('base64');

                  // Adicionar issues ao projeto
                  const parentResult = await github.graphql(addParentMutation, {
                    projectId,
                    contentId: issue.node_id
                  });

                  const childResult = await github.graphql(addParentMutation, {
                    projectId,
                    contentId: newIssue.data.node_id
                  });

                  // Criar relacionamento pai-filho usando a API correta do Projects v2
                  if (parentResult.addProjectV2ItemByContentId?.item?.id && childResult.addProjectV2ItemByContentId?.item?.id) {
                    const linkMutation = `
                      mutation($parentId: ID!, $childId: ID!) {
                        updateProjectV2ItemFieldValue(input: {
                          projectId: "${projectId}",
                          itemId: $childId,
                          fieldId: "parent",
                          value: {
                            singleSelectOptionId: $parentId
                          }
                        }) {
                          projectV2Item {
                            id
                          }
                        }
                      }
                    `;

                    // Nota: Este é um exemplo. A API real pode variar dependendo da configuração do projeto
                    console.log(`Tentando vincular ${childResult.addProjectV2ItemByContentId.item.id} como filho de ${parentResult.addProjectV2ItemByContentId.item.id}`);
                  }
                } catch (projectError) {
                  console.log(`Erro ao adicionar ao projeto: ${projectError}`);
                  // Fallback: pelo menos criar referência na descrição
                  await github.rest.issues.update({
                    owner,
                    repo,
                    issue_number: childIssueNumber,
                    body: `Sub-issue de #${parentNumber}\n\n**Relacionamento:** Esta issue é filha de #${parentNumber}`
                  });
                }
              }

              createdIssues.push(`- [ ] #${newIssue.data.number} ${line}`);
            }

            // Verifica status das sub-issues criadas
            let closedCount = 0;
            for (const line of createdIssues) {
              const issueNumber = line.match(/#(\d+)/)[1];
              const sub = await github.rest.issues.get({ owner, repo, issue_number: parseInt(issueNumber) });
              if (sub.data.state === 'closed') closedCount++;
            }

            const total = createdIssues.length;
            const tipoPlural = tipo === 'Feature' ? 'Features' : 'Tasks';
            const checklistHeader = `### Sub-issues criadas automaticamente\n${closedCount} de ${total} ${tipoPlural} concluídas\n\n${createdIssues.join('\n')}`;

            await github.rest.issues.update({
              owner,
              repo,
              issue_number: parentNumber,
              body: body + '\n\n' + checklistHeader
            });
