name: Criar Sub-Issues a partir de Epic

on:
  issues:
    types: [opened]

jobs:
  create-subissues:
    runs-on: ubuntu-latest
    steps:
      - name: Criar sub-issues e checklist
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body;
            const parentNumber = issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Função auxiliar para extrair seções
            const extract = (label) => {
              const match = body.match(new RegExp(`### ${label}[\\s\\S]*?\\n(.*?)\\n`, 'i'));
              return match ? match[1].trim() : null;
            };

            // Determinar tipo da issue
            let tipo = 'Task';
            if (issue.title.includes('[Epic]')) tipo = 'Feature';
            else if (issue.title.includes('[Feature]')) tipo = 'Task';

            // Extrair subissues
            const subissuesMatch = body.match(/### Sub-issues a serem criadas[\s\S]*?\n([\s\S]*)/);
            const subissuesRaw = subissuesMatch ? subissuesMatch[1] : '';
            const subissues = subissuesRaw.split('\n').map(l => l.trim()).filter(l => l.length > 0);

            // Campos exclusivos para Task
            let prioridade = null;
            let tipoImplementacao = null;
            let milestoneId = null;

            if (tipo === 'Task') {
              prioridade = extract('Prioridade');
              tipoImplementacao = extract('Tipo de implementação');

              const sprintName = extract('Sprint ou período de execução');
              if (sprintName) {
                const milestones = await github.rest.issues.listMilestones({ owner, repo });
                const found = milestones.data.find(m => m.title === sprintName);
                if (found) milestoneId = found.number;
              }
            }

            // Montar labels
            const labels = [tipo.toLowerCase()];
            if (prioridade) labels.push(`prioridade-${prioridade.toLowerCase()}`);
            if (tipoImplementacao) labels.push(tipoImplementacao.toLowerCase());

            const createdIssues = [];

            for (const line of subissues) {
              const issuePayload = {
                owner,
                repo,
                title: `[${tipo}] ${line}`,
                body: `Sub-issue de #${parentNumber}`,
                labels
              };

              if (tipo === 'Task' && milestoneId) {
                issuePayload.milestone = milestoneId;
              }

              const newIssue = await github.rest.issues.create(issuePayload);

              // Criar relacionamento como sub-issue (child)
              await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/relationships', {
                owner,
                repo,
                issue_number: parentNumber,
                target_issue_number: newIssue.data.number,
                relationship_type: 'child'
              });

              createdIssues.push(`- [ ] #${newIssue.data.number} ${line}`);
            }

            // Verifica status das sub-issues criadas
            let closedCount = 0;
            for (const line of createdIssues) {
              const issueNumber = line.match(/#(\d+)/)[1];
              const sub = await github.rest.issues.get({ owner, repo, issue_number: parseInt(issueNumber) });
              if (sub.data.state === 'closed') closedCount++;
            }

            const total = createdIssues.length;
            const tipoPlural = tipo === 'Feature' ? 'Features' : 'Tasks';
            const checklistHeader = `### Sub-issues criadas automaticamente\n${closedCount} de ${total} ${tipoPlural} concluídas\n\n${createdIssues.join('\n')}`;

            await github.rest.issues.update({
              owner,
              repo,
              issue_number: parentNumber,
              body: body + '\n\n' + checklistHeader
            });
